name: perinja2_thesis
cchannels:
- conda-forge
dependencies:
- pip=23.2.1
- python=3.10.0
- dill=0.3.7
- folium=0.14.0
- jupyter=1.0.0
- jupyterlab=4.0.6
- lxml=4.9.3
- matplotlib=3.8.0
- networkx=3.1
- numpy=1.26.0
- plotly=5.17.0
- pydantic=2.4.2
- pyvis=0.3.1
- pandas=2.0.0
- scipy=1.11.3
- seaborn=0.13.0
- sphinx=7.2.6
- streamlit=1.28.2
- tqdm=4.66.1
- wordcloud=1.9.2
- pip:
  - black==23.10.1
  - flake8==6.1.0
  - grandalf==0.8
  - isort==5.12.0
  - joblib==1.3.2
  - mccabe==0.7.0
  - mypy-extensions==1.0.0
  - netgraph==4.12.11
  - pathspec==0.11.2
  - pycodestyle==2.11.1
  - pydata-sphinx-theme==0.14.4
  - pyflakes==3.1.0
  - pyping==0.0.6
  - rectangle-packer==2.0.2
  - ruff==0.1.7
  - scikit-learn==1.3.2
  - streamlit-folium==0.15.0
  - threadpoolctl==3.2.0
